export const LOAD_BOARD = 'LOAD_BOARD';
export const BOARD_LOADED = 'BOARD_LOADED';
export const CANCEL_BOARD_LOADING = 'CANCEL_BOARD_LOADING';
export const BOARD_DISCOVERED = 'BOARD_DISCOVERED';
export const PROPOSAL_COUNTS = 'PROPOSAL_COUNTS';
export const CREATE_BOARD = 'CREATE_BOARD';

export const LOAD_PROPOSAL = 'LOAD_PROPOSAL';
export const PROPOSAL_LOADED = 'PROPOSAL_LOADED';
export const CANCEL_PROPOSAL_LOADING = 'CANCEL_PROPOSAL_LOADING';
export const SELECT_PROPOSAL = 'SELECT_PROPOSAL';
export const CLEAR_PROPOSALS = 'CLEAR_PROPOSALS';
export const PROPOSAL_RECENT_VOTERS = 'PROPOSAL_RECENT_VOTERS';


export const NEW_PROPOSAL = 'NEW_PROPOSAL';
export const PROPOSAL_CREATED = 'PROPOSAL_CREATED';
export const CANCEL_NEW_PROPOSAL = 'CANCEL_NEW_PROPOSAL';
export const NEW_PROPOSAL_ERROR = 'NEW_PROPOSAL_ERROR';
export const NEW_PROPOSAL_TX = 'NEW_PROPOSAL_TX';

export const LOAD_ACCOUNT = 'LOAD_ACCOUNT';
export const ACCOUNT_LOADED = 'ACCOUNT_LOADED';

export const VOTE = 'VOTE';
export const VOTE_CAST = 'VOTE_CAST';
export const VOTE_ERROR = 'VOTE_ERROR';
export const VOTE_TX = 'VOTE_TX';

export const EXECUTE = 'EXECUTE';
export const EXECUTE_TX = 'EXECUTE_TX';
export const EXECUTE_SUCCESS = 'EXECUTE_SUCCESS';
export const EXECUTE_ERROR = 'EXECUTE_ERROR';

export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_PENDING = 'TRANSACTION_PENDING';
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR';
export const TRANSACTION_SUCCESS = 'TRANSACTION_SUCCESS';

export const RULES_TRANSACTION = 'RULES_TRANSACTION';

export const LOAD_NETWORK = 'LOAD_NETWORK';
export const NETWORK_LOADED = 'NETWORK_LOADED';
